// <auto-generated />
namespace WebSolutionForModelPharmacies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_asking_price_to_product_return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_asking_price_to_product_return));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071854567_add_asking_price_to_product_return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
