// <auto-generated />
namespace WebSolutionForModelPharmacies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Address_CustomerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_CustomerId));
        
        string IMigrationMetadata.Id
        {
            get { return "201909151828592_Address_CustomerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
