// <auto-generated />
namespace WebSolutionForModelPharmacies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductReturn_Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductReturn_Status));
        
        string IMigrationMetadata.Id
        {
            get { return "201909160913371_ProductReturn_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
